# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e608f102c65249d8193bc9f84841501147db271d2654c1c2e42a8640a1f28be636cd62d64dfc437ba0d1e0721bdfd7c9f3cbd3d9254ca49e2856f924b63147db

test:
  secret_key_base: 63dc2e2b559b52c1ab92dd1131b9942a013e025e1878de6cdf051b58f0aa9d1c3917b18838c505fdab4197f7d6636357f7be811e177042729c260e46bb83071f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
